version: '3'
services:
  angular:
    build: .
    container_name: angular_app
    ports:
      - "80:80"  # Expose port 80
    volumes:
      - ./dist:/usr/share/nginx/html  # Map the dist directory to NGINX's root
    restart: always
