name: Build and Deploy Angular App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.13'

    - name: Install Dependencies
      run: npm install --force

    - name: Build Angular App
      run: npm run build --prod

    - name: Deploy to IONOS Server
      uses: appleboy/scp-action@v0.1.6
      with:
        host: 87.106.191.170
        username: sapphirix
        key: ${{ secrets.SSH_KEY }}
        source: "dist/stack-maker-fe/**"
        target: "/var/www/vhosts/ffgang.ch/stackmaker.ffgang.ch/"

