name: Build and Deploy Angular App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.13'  # This should match the version in your Dockerfile

    - name: Install Dependencies
      run: npm install --force

    - name: Build Angular App
      run: npm run build --prod  # This will build the app in the dist/ directory

    - name: Deploy to IONOS Server
      uses: appleboy/scp-action@v0.1.6
      with:
        host: 87.106.191.170
        username: sapphirix
        key: ${{ secrets.SSH_KEY }}
        source: "dist/stack-maker-fe/**"  # Only the built files
        target: "/home/sapphirix/stackmaker-fe/StackMaker"

    - name: SSH Command to Restart Docker Compose
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 87.106.191.170
        username: sapphirix
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/sapphirix/stackmaker-fe/StackMaker
          sudo docker-compose down
          sudo docker-compose up -d
